const testsData = {
"Examens biochimiques": [
    { "name": "17-OH progestérone - Sang", "page": 169, "u": false, "s": true },
    { "name": "Acide Homovanilique (HVA) - Urine", "page": 134, "u": false, "s": true },
    { "name": "Acide urique - Sang", "page": 29, "u": false, "s": false },
    { "name": "Acide urique - Urine", "page": 30, "u": false, "s": false },
    { "name": "Acide valproïque (Dépakine) - Sang", "page": 116, "u": false, "s": true },
    { "name": "Acide vanylmandelique (VMA) - Urine", "page": 133, "u": false, "s": true },
    { "name": "ACTH - Sang", "page": 31, "u": false, "s": false },
    { "name": "Activité G6PD (GLUCOSE - 6 - PHOSPHATE DÉSHYDROGÉNASE) - Sang", "page": 36, "u": false, "s": false },
    { "name": "Albumine - Sang", "page": 32, "u": false, "s": false },
    { "name": "Aldostérone active plasmatique - Sang", "page": 118, "u": false, "s": true },
    { "name": "Alpha 1 – antitrypsine (AAT) - Sang", "page": 117, "u": false, "s": true },
    { "name": "Alpha Foetoprotéine (AFP) - Sang", "page": 115, "u": false, "s": true },
    { "name": "Ammoniaque - Sang", "page": 114, "u": false, "s": true },
    { "name": "Amylase - Sang", "page": 34, "u": false, "s": false },
    { "name": "Amylase - Urine", "page": 35, "u": false, "s": false },
    { "name": "Amylase – liquides d’épanchement", "page": 33, "u": false, "s": false },
    { "name": "Anticorps anti NMDA dans LCR - Sang", "page": 127, "u": false, "s": true },
    { "name": "Anticorps anti Thyroperoxydase (ATPO) - Sang", "page": 129, "u": false, "s": true },
    { "name": "Anticorps Anti-transglutaminase (IgA) – Sang", "page": 126, "u": false, "s": true },
    { "name": "Anticorps anti-ADN natif - Sang", "page": 124, "u": false, "s": true },
    { "name": "Anticorps anti-cytoplasme des polynucléaires (ANCA) - Sang", "page": 131, "u": false, "s": true },
    { "name": "Anticorps anti-ENA (antigènes nucléaires solubles) - Sang", "page": 125, "u": false, "s": true },
    { "name": "Anticorps anti-GAD - Sang", "page": 128, "u": false, "s": true },
    { "name": "Anticorps anti-ilôts de Langherans - Sang", "page": 120, "u": false, "s": true },
    { "name": "Anticorps anti-insuline - Sang", "page": 121, "u": false, "s": true },
    { "name": "Anticorps anti-LC1 (Cytosol hépatique) - Sang", "page": 122, "u": false, "s": true },
    { "name": "Anticorps anti-mitochondries - Sang", "page": 123, "u": false, "s": true },
    { "name": "Anticorps anti-muscles lisses - Sang", "page": 132, "u": false, "s": true },
    { "name": "Anticorps anti-neuronaux - Sang", "page": 130, "u": false, "s": true },
    { "name": "Anticorps anti-nucléaires (AAN) - Sang", "page": 119, "u": false, "s": true },
    { "name": "Benzodiazépine - Sang", "page": 135, "u": false, "s": true },
    { "name": "Beta HCG - Sang", "page": 136, "u": false, "s": true },
    { "name": "Bicarbonates (OU Réserve Alcaline) - sang", "page": 37, "u": false, "s": false },
    { "name": "Bilirubines: Totale + Conjuguée - Sang", "page": 38, "u": false, "s": false },
    { "name": "CA 125 - Sang", "page": 140, "u": false, "s": true },
    { "name": "Calcium - sang", "page": 39, "u": false, "s": false },
    { "name": "Calcium - Urine", "page": 40, "u": false, "s": false },
    { "name": "Calculs urinaires - Urine", "page": 142, "u": false, "s": true },
    { "name": "Carbamazepine (Tégrétol) - Sang", "page": 143, "u": false, "s": true },
    { "name": "CarbOxyHémoglobine Artérielle (COHB) – Sang artériel", "page": 41, "u": true, "s": false },
    { "name": "Céruléoplasmine - Sang", "page": 137, "u": false, "s": true },
    { "name": "Chimie Des Urines (Bandelettes Urinaires) - Urine", "page": 42, "u": false, "s": false },
    { "name": "Chlorure (Cl Ur) - Urine", "page": 43, "u": false, "s": false },
    { "name": "Cholestérol Total (Chol T) - Sang", "page": 44, "u": false, "s": false },
    { "name": "Cholestérol – liquides d’épanchement", "page": 45, "u": false, "s": false },
    { "name": "CK (Créatine Kinase) - Sang", "page": 47, "u": false, "s": false },
    { "name": "Clairance de l'α-1 antitrypsine - Selles", "page": 141, "u": false, "s": true },
    { "name": "Contrôle PCR Sur Gel D’agarose", "page": 108, "u": false, "s": false },
    { "name": "Cortisol - Sang", "page": 46, "u": false, "s": false },
    { "name": "C-Reactive Protein (CRP) - Sang", "page": 48, "u": false, "s": false },
    { "name": "Créatinine - Sang", "page": 49, "u": false, "s": false },
    { "name": "Créatinine – Urine", "page": 50, "u": false, "s": false },
    { "name": "Cuivre - Sang", "page": 138, "u": false, "s": true },
    { "name": "Cuivre - Urine", "page": 139, "u": false, "s": true },
    { "name": "Dépakine - Sang", "page": 146, "u": false, "s": true },
    { "name": "Dérivés méthoxylés urinaire de 24 heures -Urine", "page": 145, "u": false, "s": true },
    { "name": "Digestion Enzymatique", "page": 109, "u": false, "s": false },
    { "name": "Dosage du CH50 (complément hémolytique total) - Sang", "page": 144, "u": false, "s": true },
    { "name": "Dosage Pondéral Des Immunoglobulines (Ig G, IgA, IgM) - Sang", "page": 51, "u": false, "s": false },
    { "name": "Electrophorèse Des Protéines Sériques (EPP) - Sang", "page": 52, "u": false, "s": false },
    { "name": "Enolase Neuro Spécifique (NSE) - Sang", "page": 150, "u": false, "s": true },
    { "name": "Enzyme de conversion de l'angiotensine (ECA) - LCR", "page": 148, "u": false, "s": true },
    { "name": "Enzyme de conversion de l'angiotensine (ECA) - Sang", "page": 147, "u": false, "s": true },
    { "name": "Epreuve à l’Insuline: Dosage du Cortisol - Sang", "page": 54, "u": false, "s": false },
    { "name": "Epreuve à l’insuline: Dosage du glucose - Sang", "page": 56, "u": false, "s": false },
    { "name": "Epreuve à L’Insuline: Dosage du GH - Sang", "page": 55, "u": false, "s": false },
    { "name": "Epreuve au Glucagon: Dosage du Cortisol - Sang", "page": 59, "u": false, "s": false },
    { "name": "Epreuve au Glucagon: Dosage du Glucose - Sang", "page": 58, "u": false, "s": false },
    { "name": "Epreuve au Glucagon: Dosage la GH - Sang", "page": 57, "u": false, "s": false },
    { "name": "Epreuve Test LH-RH (Dosage de FSH et LH) - Sang", "page": 53, "u": false, "s": false },
    { "name": "Extraction ADN", "page": 110, "u": false, "s": false },
    { "name": "Fer (SIDERÉMIE) - Sang", "page": 61, "u": false, "s": false },
    { "name": "Ferritine - Sang", "page": 62, "u": false, "s": false },
    { "name": "FSH - Sang", "page": 63, "u": false, "s": false },
    { "name": "FT4 - Sang", "page": 64, "u": false, "s": false },
    { "name": "Gamma Glutamyl Transférase (GGT) - Sang", "page": 65, "u": false, "s": false },
    { "name": "Gaz Du Sang", "page": 66, "u": true, "s": false },
    { "name": "Gentamicine - Sang", "page": 152, "u": false, "s": true },
    { "name": "Glucose - Sang", "page": 67, "u": false, "s": false },
    { "name": "Glucose - Urine", "page": 68, "u": false, "s": false },
    { "name": "Glucose Post Prandial (GPP) - Sang", "page": 69, "u": false, "s": false },
    { "name": "Haptoglobine - Sang", "page": 153, "u": false, "s": true },
    { "name": "HbA1c - Sang", "page": 71, "u": false, "s": false },
    { "name": "Homocystéine- Sang", "page": 154, "u": false, "s": true },
    { "name": "Hormone de croissance (GH) – Sang", "page": 70, "u": false, "s": false },
    { "name": "HyperGlycémie Provoquée Par Voie Orale (HGPO) - Sang", "page": 72, "u": false, "s": false },
    { "name": "Immunofixation - Sang", "page": 156, "u": false, "s": true },
    { "name": "Immunoglobulines E totales (IgE) - Sang", "page": 73, "u": false, "s": false },
    { "name": "Insulin-like growth factor-1 (IGF-1) - Sang", "page": 155, "u": false, "s": true },
    { "name": "Insuline - Sang", "page": 157, "u": false, "s": true },
    { "name": "Ionogramme Sanguin (Na, K, Cl) - Sang", "page": 74, "u": false, "s": false },
    { "name": "Isoniazide - Sang", "page": 158, "u": false, "s": true },
    { "name": "Lactate - Sang", "page": 159, "u": false, "s": true },
    { "name": "Lamotrigine - Sang", "page": 160, "u": false, "s": true },
    { "name": "LDH (Lactate DésHydrogènase) - Sang", "page": 76, "u": false, "s": false },
    { "name": "LDH - liquides d’épanchement", "page": 77, "u": false, "s": false },
    { "name": "Les Compléments: C3 et C4 - Sang", "page": 75, "u": false, "s": false },
    { "name": "LH - Sang", "page": 78, "u": false, "s": false },
    { "name": "Lipase - Sang", "page": 161, "u": false, "s": true },
    { "name": "Liquide Céphalo-Rachidien (LCR): Glucose, Protéines, Chlorure", "page": 79, "u": true, "s": false },
    { "name": "Magnésium - Sang", "page": 80, "u": false, "s": false },
    { "name": "Magnésium - Urine", "page": 81, "u": false, "s": false },
    { "name": "Microalbumine - Urine", "page": 82, "u": false, "s": false },
    { "name": "NT Pro BNP - Sang", "page": 162, "u": false, "s": true },
    { "name": "Oestradiol - Sang", "page": 83, "u": false, "s": false },
    { "name": "Paracétamol - Sang", "page": 165, "u": false, "s": true },
    { "name": "Paracétamol - Sang (Toxicologie)", "page": 167, "u": false, "s": false },
    { "name": "Parathormone (PTH) - Sang", "page": 85, "u": false, "s": false },
    { "name": "PCR MULTIPLEX", "page": 112, "u": false, "s": false },
    { "name": "PCR SIMPLE", "page": 111, "u": false, "s": false },
    { "name": "Peptide C - Sang", "page": 164, "u": false, "s": true },
    { "name": "Phénobarbital - Sang", "page": 168, "u": false, "s": true },
    { "name": "Phénytoine - Sang", "page": 166, "u": false, "s": true },
    { "name": "Phosphatases alcalines (PAL) - Sang", "page": 84, "u": false, "s": false },
    { "name": "Phosphore - Sang", "page": 86, "u": false, "s": false },
    { "name": "Phosphore - Urine", "page": 87, "u": false, "s": false },
    { "name": "Potassium - Urine", "page": 88, "u": false, "s": false },
    { "name": "Procalcitonine - Sang", "page": 89, "u": false, "s": false },
    { "name": "Prolactine - Sang", "page": 163, "u": false, "s": true },
    { "name": "Protéines Plasmatiques - Sang", "page": 90, "u": false, "s": false },
    { "name": "Protéines Urinaire (Protéinurie) - Urine", "page": 91, "u": false, "s": false },
    { "name": "Protides – liquides d’épanchement", "page": 92, "u": false, "s": false },
    { "name": "Séquençage d’ADN", "page": 113, "u": false, "s": false },
    { "name": "Sodium - Urine", "page": 93, "u": false, "s": false },
    { "name": "Sulfate de déhydroépiandrostérone (SDHA) - Sang", "page": 171, "u": false, "s": true },
    { "name": "Test à HCG: Dosage d’Oestradiol - Sang", "page": 97, "u": false, "s": false },
    { "name": "Test à HCG: Dosage de Testostérone - Sang", "page": 96, "u": false, "s": false },
    { "name": "Test à la Dexaméthasone: Dosage du Cortisol - Sang", "page": 100, "u": false, "s": false },
    { "name": "Test à la Sueur - Sueur", "page": 95, "u": false, "s": false },
    { "name": "Test au Synacthène: Dosage du Cortisol - Sang", "page": 98, "u": false, "s": false },
    { "name": "Test Dexaméthasone: Dosage ACTH - Sang", "page": 99, "u": false, "s": false },
    { "name": "Testostérone - Sang", "page": 94, "u": false, "s": false },
    { "name": "Transaminases (ASAT, ALAT) - Sang", "page": 101, "u": false, "s": false },
    { "name": "Triglycérides (TG) - Sang", "page": 102, "u": false, "s": false },
    { "name": "Triglycérides – liquides d’épanchement", "page": 103, "u": false, "s": false },
    { "name": "Troponine - Sang", "page": 172, "u": false, "s": true },
    { "name": "TSH - Sang", "page": 104, "u": false, "s": false },
    { "name": "Urée - Sang", "page": 105, "u": false, "s": false },
    { "name": "Urée - Urine", "page": 106, "u": false, "s": false },
    { "name": "Vancomycine - Sang", "page": 180, "u": false, "s": true },
    { "name": "VITAMINE A - Sang", "page": 173, "u": false, "s": true },
    { "name": "VITAMINE B1 (Thiamine) - Sang", "page": 176, "u": false, "s": true },
    { "name": "VITAMINE B12 (Cobalamine) - Sang", "page": 179, "u": false, "s": true },
    { "name": "VITAMINE B6 (Phosphate de pyridoxal) - Sang", "page": 177, "u": false, "s": true },
    { "name": "VITAMINE B9 (Acide Folique) - Sang", "page": 178, "u": false, "s": true },
    { "name": "VITAMINE C - Sang", "page": 174, "u": false, "s": true },
    { "name": "VITAMINE E - Sang", "page": 175, "u": false, "s": true },
    { "name": "Vitamine D Totale - Sang", "page": 107, "u": false, "s": false },
    { "name": "Voriconazole - Sang", "page": 181, "u": false, "s": true }
],
"Examens hématologiques": [
    { "name": "Anti HLA", "page": 235, "u": false, "s": true },
    { "name": "Antithrombine/ AT", "page": 186, "u": false, "s": false },
    { "name": "Caryotype", "page": 228, "u": false, "s": true },
    { "name": "Cross match", "page": 236, "u": false, "s": true },
    { "name": "Cross-match: test de compatibilité majeur par TCI/test de compatibilité au laboratoire", "page": 187, "u": true, "s": false },
    { "name": "Cytochimie MPO / Myéloperoxydase", "page": 188, "u": false, "s": false },
    { "name": "Détermination autres antigènes érythrocytaires chacun", "page": 190, "u": true, "s": false },
    { "name": "Détermination du groupe sanguin ABO-RH (D) standard", "page": 189, "u": true, "s": false },
    { "name": "Dosage de la Protéine C", "page": 192, "u": false, "s": false },
    { "name": "Dosage de la Protéine S (activité, libre, totale)", "page": 191, "u": false, "s": false },
    { "name": "Dosage des D-Dimères par agglutination/D-Dimères", "page": 203, "u": true, "s": false },
    { "name": "Dosage du Facteur anti hémophilique A (Facteur VIII)", "page": 198, "u": false, "s": false },
    { "name": "Dosage du Facteur anti hémophilique B (facteur IX)", "page": 201, "u": false, "s": false },
    { "name": "Dosage du Facteur Hageman (facteur XII)", "page": 195, "u": false, "s": false },
    { "name": "Dosage du Facteur XI (Facteur Rosenthal)", "page": 196, "u": false, "s": false },
    { "name": "Dosage du Fibrinogène (facteur I)", "page": 193, "u": true, "s": false },
    { "name": "Dosage fonctionnel du Facteur de stabilisation de la fibrine (facteur XIII)", "page": 194, "u": false, "s": false },
    { "name": "Dosage fonctionnel du Facteur II (Thrombine)", "page": 202, "u": false, "s": false },
    { "name": "Dosage fonctionnel du Facteur V (proaccélérine)", "page": 200, "u": false, "s": false },
    { "name": "Dosage fonctionnel du Facteur VII(Proconvertine)", "page": 199, "u": false, "s": false },
    { "name": "Dosage fonctionnel du Facteur X (Facteur Stuart)", "page": 197, "u": false, "s": false },
    { "name": "Epreuve d’élution ou d’adsorption d’anticorps anti-érythrocytaire", "page": 237, "u": false, "s": true },
    { "name": "Epreuve d’élution ou d’adsorption d’anticorps anti-érythrocytaire", "page": 238, "u": false, "s": true },
    { "name": "Etude des fonctions plaquettaires (adhésion, agrégation)", "page": 204, "u": false, "s": false },
    { "name": "Etude des fonctions plaquettaires (adhésion, agrégation)", "page": 242, "u": false, "s": true },
    { "name": "Facteur Von Willebrand antigène/FVW:Ag", "page": 205, "u": false, "s": false },
    { "name": "Hémogramme", "page": 206, "u": true, "s": false },
    { "name": "Héparinémie anti Xa/Activité anti Xa", "page": 207, "u": false, "s": false },
    { "name": "Immunophénotypage des hémopathies cytométrie de flux /Immunophénotypage leucocytaire", "page": 208, "u": false, "s": false },
    { "name": "MRD des hémopathies malignes par cytométrie de flux", "page": 210, "u": false, "s": false },
    { "name": "Myélogramme", "page": 209, "u": false, "s": false },
    { "name": "Numération des réticulocytes", "page": 211, "u": true, "s": false },
    { "name": "Quantification CD34", "page": 239, "u": false, "s": true },
    { "name": "Quantification du transcrit bcr-abl", "page": 229, "u": false, "s": true },
    { "name": "RAI avec panel d’hématies dépistage TCI / recherche des agglutinines irrégulières", "page": 212, "u": true, "s": false },
    { "name": "RAI Identification", "page": 240, "u": false, "s": true },
    { "name": "Recherche d’anticoagulant circulant de type lupique/ Lupus anticoagulant", "page": 217, "u": false, "s": false },
    { "name": "Recherche d’anticorps anti-facteur (titrage) / anticoagulant circulant anti-facteur", "page": 216, "u": false, "s": false },
    { "name": "Recherche de corps de Heinz", "page": 218, "u": false, "s": false },
    { "name": "Recherche de la mutation FLT3 ITD", "page": 231, "u": false, "s": true },
    { "name": "Recherche de la mutation JAK2V617F", "page": 232, "u": false, "s": true },
    { "name": "Recherche de la mutation NPM1", "page": 233, "u": false, "s": true },
    { "name": "Recherche des drépanocytes (test de falciformation) / test d’Emmel", "page": 213, "u": false, "s": false },
    { "name": "Recherche des produits de dégradation de la fibrine et/ou fibrinogène (PDF)", "page": 219, "u": false, "s": false },
    { "name": "Recherche du transcrit bcr-abl", "page": 230, "u": false, "s": true },
    { "name": "Recherche du transcrit PML-RARA", "page": 234, "u": false, "s": true },
    { "name": "Résistance à la protéine C activée (RPCA)", "page": 215, "u": false, "s": false },
    { "name": "Résistance globulaire osmotique / fragilité osmotique", "page": 214, "u": false, "s": false },
    { "name": "Test coombs direct avec anti-globuline polyvalente/TCD dépistage", "page": 220, "u": true, "s": false },
    { "name": "Test coombs direct avec anti-globuline spécifique /TCD", "page": 221, "u": true, "s": false },
    { "name": "Temps de céphaline avec activateur/TCA/TCK", "page": 225, "u": true, "s": false },
    { "name": "Temps de quick/TQ/Taux de prothrombine/TP", "page": 223, "u": true, "s": false },
    { "name": "Temps de saignement/ TS", "page": 224, "u": false, "s": false },
    { "name": "Temps de thombine", "page": 222, "u": false, "s": false },
    { "name": "Typage HLA", "page": 241, "u": false, "s": true },
    { "name": "Vitesse de sédimentation / VS", "page": 226, "u": true, "s": false }
],
"Examens microbiologiques": [
    { "name": "Antibiogramme", "page": 246, "u": false, "s": false },
    { "name": "Anticorps anti-Streptolysine O : ASLO", "page": 280, "u": false, "s": false },
    { "name": "Antigènes solubles bactériens", "page": 277, "u": true, "s": false },
    { "name": "Antigènes viraux dans les selles (Rotavirus/ Adenovirus)", "page": 278, "u": false, "s": false },
    { "name": "Bartonella: Sérologie (Maladie Des Griffes De Chat)", "page": 307, "u": false, "s": true },
    { "name": "BMR: Recherche de bactéries multirésistantes", "page": 279, "u": false, "s": false },
    { "name": "Borrelia burgdorferi complex : Sérologie (IgM et IgG) Maladie de Lyme", "page": 283, "u": false, "s": false },
    { "name": "Borrelia burgdorferii : PCR Maladie de Lyme", "page": 297, "u": false, "s": true },
    { "name": "Brucellose: Sérologie de Wright (IgM) et Rose Bengale (IgG)", "page": 282, "u": false, "s": false },
    { "name": "Campylobacter : Sérologie", "page": 308, "u": false, "s": true },
    { "name": "CHARGE VIRALE VIH :VIRUS DE L'IMMUNODÉFICIENCE HUMAINE", "page": 296, "u": false, "s": true },
    { "name": "Chlamydia pneumoniae : Sérologie IgM et IgG", "page": 309, "u": false, "s": true },
    { "name": "Concentration minimale inhibitrice d’un antibiotique (CMI)", "page": 256, "u": false, "s": false },
    { "name": "Coproculture standard", "page": 247, "u": false, "s": false },
    { "name": "Coqueluche : PCR (Bordetella pertussis ou parapertussis)", "page": 249, "u": false, "s": false },
    { "name": "Coqueluche: Sérologie", "page": 310, "u": false, "s": true },
    { "name": "Coxiella burnetti : Sérologie", "page": 311, "u": false, "s": true },
    { "name": "Culot urinaire", "page": 248, "u": true, "s": false },
    { "name": "Cytomégalovirus : Sérologie CMV (IgM et IgG)", "page": 281, "u": false, "s": false },
    { "name": "Cytomegalovirus : PCR CMV", "page": 250, "u": false, "s": false },
    { "name": "Dispositifs intravasculaires", "page": 258, "u": true, "s": false },
    { "name": "ECBC: Examen cytobactériologique des crachats", "page": 260, "u": false, "s": false },
    { "name": "ECBU: Examen cytobactériologique des urines", "page": 261, "u": true, "s": false },
    { "name": "Enterovirus : PCR", "page": 251, "u": false, "s": false },
    { "name": "Epstein Barr Virus : Sérologie EBV (IgM et IgG)", "page": 289, "u": false, "s": false },
    { "name": "Epstein Barr Virus: PCR EBV", "page": 252, "u": false, "s": false },
    { "name": "Helicobacter pylori : Sérologie", "page": 313, "u": false, "s": true },
    { "name": "Hémocultures", "page": 264, "u": true, "s": false },
    { "name": "Hépatite A : Sérologie (IgM – VHA)", "page": 314, "u": false, "s": true },
    { "name": "Hépatite B : Sérologie (Ag HBs)", "page": 284, "u": false, "s": false },
    { "name": "Hépatite B : Sérologie (Anticorps anti HBc totaux)", "page": 286, "u": false, "s": false },
    { "name": "Hépatite B : Sérologie (Anticorps anti Hbe)", "page": 316, "u": false, "s": true },
    { "name": "Hépatite B : Sérologie (Anticorps anti HBs)", "page": 285, "u": false, "s": false },
    { "name": "Hépatite B : Sérologie (Antigène Hbe)", "page": 317, "u": false, "s": true },
    { "name": "Hépatite B : Sérologie(Anticorps anti HBc IgM)", "page": 315, "u": false, "s": true },
    { "name": "Hépatite B: PCR VHB (recherche et quantification)", "page": 299, "u": false, "s": true },
    { "name": "Hépatite C : Sérologie(HCV)", "page": 287, "u": false, "s": false },
    { "name": "Hépatite C: PCR VHC (recherche et quantification)", "page": 300, "u": false, "s": true },
    { "name": "Hépatite D : Sérologie (IgG VHD)", "page": 319, "u": false, "s": true },
    { "name": "Hépatite D : Sérologie (IgM VHD)", "page": 320, "u": false, "s": true },
    { "name": "Hépatite D : Sérologie Antigène Delta (VHD)", "page": 318, "u": false, "s": true },
    { "name": "Hépatite E : Sérologie IgM/IgG VHE", "page": 321, "u": false, "s": true },
    { "name": "Herpes Simplex Virus 1 et 2: PCR HSV1 et 2", "page": 253, "u": false, "s": false },
    { "name": "Human Herpes Virus : PCR HHV6", "page": 301, "u": false, "s": true },
    { "name": "Human Herpes Virus 6 : Sérologie (IgM/IgG - HHV 6)", "page": 322, "u": false, "s": true },
    { "name": "Sérologie Human Herpes Virus 8 : IgG HHV 8", "page": 323, "u": false, "s": true },
    { "name": "Index de colonisation", "page": 265, "u": false, "s": false },
    { "name": "Interféron gamma (Tuberculosis)", "page": 259, "u": false, "s": false },
    { "name": "Lavage broncho-alvéolaire : examen cytobactériologique", "page": 266, "u": true, "s": false },
    { "name": "Legionella pneumophila : Sérologie", "page": 324, "u": false, "s": true },
    { "name": "Leptospirose : Sérologie", "page": 325, "u": false, "s": true },
    { "name": "Liquide articulaire : Examen cytobactériologique", "page": 262, "u": true, "s": false },
    { "name": "Liquide cérébrospinal (LCS): Examen cytobactériologique", "page": 263, "u": true, "s": false },
    { "name": "Liquides de ponction (liquide pleural, d’ascite, péricardique, de dialyse péritonéale)", "page": 267, "u": true, "s": false },
    { "name": "Mycobactéries: Examen direct + culture", "page": 303, "u": false, "s": true },
    { "name": "Mycobacterium tuberculosis (BK): PCR", "page": 304, "u": false, "s": true },
    { "name": "Mycoplasma Pneumoniae : Sérologie (IgM et IgG)", "page": 290, "u": false, "s": false },
    { "name": "Oreillons : Sérologie IgM/IgG", "page": 326, "u": false, "s": true },
    { "name": "Parvovirus B19 : Sérologie (IgM et IgG)", "page": 291, "u": false, "s": false },
    { "name": "Parvovirus B19: PCR", "page": 305, "u": false, "s": true },
    { "name": "PCR Multiplex Gastro-intestinale", "page": 268, "u": false, "s": false },
    { "name": "PCR Multiplex Neuro-méningée", "page": 269, "u": false, "s": false },
    { "name": "PCR Multiplex Respiratoire", "page": 270, "u": false, "s": false },
    { "name": "Pneumocoque, Méningocoque et Haemophilus influenzae : PCR infections invasives", "page": 257, "u": false, "s": false },
    { "name": "Poliovirus : PCR", "page": 306, "u": false, "s": true },
    { "name": "Prélèvement de gorge", "page": 271, "u": true, "s": false },
    { "name": "Prélèvement ORL", "page": 272, "u": true, "s": false },
    { "name": "Prélèvement trachéal (PT): examen cytobactériologique", "page": 274, "u": true, "s": false },
    { "name": "Prélèvement trachéal protégé (PTP)", "page": 275, "u": true, "s": false },
    { "name": "Prélèvements ostéo-articulaires", "page": 273, "u": true, "s": false },
    { "name": "Pus divers", "page": 276, "u": true, "s": false },
    { "name": "Rickettsioses: Sérologie (CONORI / TYPHI)", "page": 327, "u": false, "s": true },
    { "name": "rougeole: Sérologie IgM et IgG", "page": 328, "u": false, "s": true },
    { "name": "Rubéole : Sérologie (IgM et IgG)", "page": 292, "u": false, "s": false },
    { "name": "SARS-CoV-2 : PCR COVID19", "page": 254, "u": false, "s": false },
    { "name": "Syphilis : Sérologie (TPHA)", "page": 288, "u": false, "s": false },
    { "name": "Syphilis :Sérologie de confirmation IgM", "page": 312, "u": false, "s": true },
    { "name": "Toxoplasmose : Sérologie (IgM et IgG)", "page": 293, "u": false, "s": false },
    { "name": "Varicelle Zona Virus: Sérologie IgM et IgG (VZV)", "page": 329, "u": false, "s": true },
    { "name": "VIH :Virus de l'immunodéficience humaine : PCR (Charge virale)", "page": 296, "u": false, "s": true },
    { "name": "VIH :Virus de l'immunodéficience humaine: Sérologie (Anti VIH1, VIH2 et Antigène P24)", "page": 294, "u": false, "s": false },
    { "name": "Virus Varicelle- Zona : PCR VZV", "page": 255, "u": false, "s": false },
    { "name": "West Nile Virus : PCR (WNV)", "page": 302, "u": false, "s": true },
    { "name": "West nile Virus: Sérologie IgM ET IgG (WNV)", "page": 330, "u": false, "s": true },
    { "name": "Western Blot VIH", "page": 331, "u": false, "s": true }
]
};
